"""Initialisation des tables

Revision ID: 794584d7577a
Revises: 
Create Date: 2025-02-03 16:11:05.417309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794584d7577a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('classe', sa.String(length=50), nullable=False),
    sa.Column('poste', sa.String(length=100), nullable=False),
    sa.Column('sexe', sa.String(length=10), nullable=False),
    sa.Column('cout_repas', sa.Numeric(), nullable=False),
    sa.Column('cout_logement', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personnel')
    # ### end Alembic commands ###
