"""Ajout du modèle Decompte

Revision ID: ad0d66cf8881
Revises: 794584d7577a
Create Date: 2025-02-04 08:56:10.389948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0d66cf8881'
down_revision = '794584d7577a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decompte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('numero_ordre', sa.String(length=50), nullable=False),
    sa.Column('date_ordre', sa.Date(), nullable=False),
    sa.Column('date_depart', sa.Date(), nullable=False),
    sa.Column('date_retour', sa.Date(), nullable=False),
    sa.Column('nombre_jours', sa.Integer(), nullable=False),
    sa.Column('nombre_repas', sa.Integer(), nullable=False),
    sa.Column('nombre_nuitees', sa.Integer(), nullable=False),
    sa.Column('frais_restauration', sa.Numeric(), nullable=False),
    sa.Column('frais_logement', sa.Numeric(), nullable=False),
    sa.Column('total_paye', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decompte')
    # ### end Alembic commands ###
