"""Ajout des colonnes de frais supplémentaires

Revision ID: b512ee1fab2b
Revises: d038aa4c289f
Create Date: 2025-02-05 15:17:01.009068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b512ee1fab2b'
down_revision = 'd038aa4c289f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decompte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frais_transport_aller', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('frais_transport_retour', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('frais_peage_aller', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('frais_peage_retour', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decompte', schema=None) as batch_op:
        batch_op.drop_column('frais_peage_retour')
        batch_op.drop_column('frais_peage_aller')
        batch_op.drop_column('frais_transport_retour')
        batch_op.drop_column('frais_transport_aller')

    # ### end Alembic commands ###
