"""Ajout de la colonne interim dans Responsable

Revision ID: be3884cb1890
Revises: 3a1cca746e29
Create Date: 2025-02-07 09:16:48.007492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3884cb1890'
down_revision = '3a1cca746e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personnel', schema=None) as batch_op:
        batch_op.alter_column('division_regionale',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('responsable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interim', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsable', schema=None) as batch_op:
        batch_op.drop_column('interim')

    with op.batch_alter_table('personnel', schema=None) as batch_op:
        batch_op.alter_column('division_regionale',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
