"""Ajout du numéro d'ordre unique

Revision ID: c4a93526c3f9
Revises: ad0d66cf8881
Create Date: 2025-02-04 14:04:27.069836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a93526c3f9'
down_revision = 'ad0d66cf8881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decompte', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['numero_ordre'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decompte', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
